/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.20).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package health.hbp.api.stub.iface;

import health.hbp.api.stub.model.Edible;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2022-01-29T12:28:12.156-03:00[America/Argentina/Buenos_Aires]")
@Api(value = "hbp", description = "the hbp API")
public interface HbpApi {

    @ApiOperation(value = "Adds new edible", nickname = "addEdible", notes = "Adds a new edible", response = String.class, tags={ "edible", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Edible added. New edible ID is returned", response = String.class) })
    @RequestMapping(value = "/hbp/api/v1.0/edibles",
        produces = { "text/plain" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<String> addEdible(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Edible body
);


    @ApiOperation(value = "Delete an edible", nickname = "deleteEdible", notes = "Removes an existing edible", response = String.class, tags={ "edible", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Edible deleted", response = String.class) })
    @RequestMapping(value = "/hbp/api/v1.0/edibles/{id}",
        produces = { "text/plain" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<String> deleteEdible(@ApiParam(value = "Edible ID",required=true) @PathVariable("id") String id
);


    @ApiOperation(value = "Retrieve all edibles", nickname = "getAllEdibles", notes = "This end-point return the complete list of available edibles", response = Edible.class, responseContainer = "List", tags={ "edible", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Everything OK", response = Edible.class, responseContainer = "List") })
    @RequestMapping(value = "/hbp/api/v1.0/edibles",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Edible>> getAllEdibles();


    @ApiOperation(value = "Retrieve an edible information", nickname = "retrieveEdible", notes = "Retrieves complete information of an edible", response = Edible.class, tags={ "edible", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Edible.class) })
    @RequestMapping(value = "/hbp/api/v1.0/edibles/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Edible> retrieveEdible(@ApiParam(value = "Edible ID",required=true) @PathVariable("id") String id
);


    @ApiOperation(value = "Updates an existing edible", nickname = "updateEdible", notes = "", response = String.class, tags={ "edible", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Edible updated", response = String.class) })
    @RequestMapping(value = "/hbp/api/v1.0/edibles/{id}",
        produces = { "text/plain" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<String> updateEdible(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Edible body
,@ApiParam(value = "Edible ID",required=true) @PathVariable("id") String id
);

}
