/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.20).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package health.hbp.api.stub.iface;

import health.hbp.api.stub.model.Edible;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2022-01-23T11:37:42.623-03:00[America/Argentina/Buenos_Aires]")
@Api(value = "hbp", description = "the hbp API")
public interface HbpApi {

    @ApiOperation(value = "Retrieve all edibles", nickname = "getAllEdibles", notes = "This end-point return the complete list of available edibles", response = Edible.class, responseContainer = "List", tags={ "edible", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Everything OK", response = Edible.class, responseContainer = "List") })
    @RequestMapping(value = "/hbp/api/v1.0/edibles",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Edible>> getAllEdibles();

}
